# Generated by Django 4.2.5 on 2023-10-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusers',
            name='password',
        ),
    ]
